version: '3'

services:
  db:
    container_name: crud_nest_db
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
